### ISSUE TITLE
Use custom toast to expose full error tracebacks to users 

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#1]
Currently when any action in DART fails, we only show a static toast with the message "Failed :(" and log the error message in the javascript console.

I think we should use Angular's custom toast to expose this message through the UI. We can use the model  similar to the custom toast example here: https://material.angularjs.org/latest/demo/toast

Users will be able to click "More Info" to see the full traceback. Thoughts?

![screen shot 2016-04-11 at 10 16 28 am](https://cloud.githubusercontent.com/assets/2461323/14432156/80ab0b22-ffce-11e5-9a3e-1d2ff37e0968.png)

**Comment by dannymcpherson** [comment]
lgtm
