### ISSUE TITLE
dataset_from_existing_s3_path: allow users to enter a s3 prefix instead of full path

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#13]
```dataset_guess``` feature in dart should let users enter an s3 prefix path (possibly a dataset prefix path) instead of having to enter a full valid s3 path to a file. This adds better usability of the feature since it's difficult to remember an exact s3 path.

It would be cool if dart could retrieve the last modified file i.e. latest file in the prefix. @dannymcpherson is there anything in dart already that we could leverage to do this? Or should we just use [list_objects_v2 in boto3](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.list_objects_v2) and iterate through the list to find the latest file. I worry that this operation may take too long. Any suggestions?

**Comment by dannymcpherson** [comment]
Yep - this feature makes sense.  And I agree - the moment you specify a prefix, there is a trade off between speed and accuracy.  In this case, I vote for speed.  How about just grab the first file?  If the user doesn't like the guessed results, they can try again with a "deeper" prefix.  What do you think?

And no... I don't know of pre-existing dart code that would specifically help out here.

**Comment by maybeiambatman** [comment]
@jsteigs642 you wanted it, you got it. review please?
