### ISSUE TITLE
Dart actions get stuck in 'PENDING' state if task container isn't created

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#140]
When dart actions fail to create containers on AWS Batch with a CannotCreateContainer Error, the action stays in 'PENDING' state since the action never gets checked out. Even though these tasks never actually ran, the action is udpated with the batch_job_id before it's even created. Because the engine worker only queues actions that are 'PENDING' and don't have a batch_job_id, these actions get stuck in a 'PENDING' state where they do have a batch_job_id.

We need to transition these actions to 'FAILED' state to reflect them in the database accurately.

**Comment by ophiradi** [comment]
This problem exist with ECS too.  It just surfaced with Batch.
