### ISSUE TITLE
Allow "_" in regex validation when creating usernames for datastores

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#21]

**Comment by dannymcpherson** [comment]
Here's the reason not to allow underscore (they are disallowed in Redshift master usernames):
http://docs.aws.amazon.com/redshift/latest/mgmt/amazon-redshift-limits.html

**Comment by maybeiambatman** [comment]
Thanks for pointing it out @dannymcpherson !
