### ISSUE TITLE
Perform client side validation on CRON expressions for Scheduled Triggers

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#3]
Angular Schema Form allows us to validate cron patterns via regex filters. Investigate if this is possible to fit the definition of permitted AWS Cron Expressions.

AWS Cron Expression Guide: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/ScheduledEvents.html

**Comment by dannymcpherson** [comment]
Take a look at ASF custom validation:
https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#custom-validation

**Comment by maybeiambatman** [comment]
After thinking about it, I think it would be better if we did this on server side just because Amazon has very unique specifications for what is a valid CRON expression.

**Comment by dannymcpherson** [comment]
Should this be closed out?

**Comment by maybeiambatman** [comment]
Yeah. I will create a follow up issue for performing this in the backend.
