### ISSUE TITLE
EMR clusters do not support scheduled triggers because of invalid cluster state

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#31]
EMR clusters will set cluster.state to DONE once they are terminated.

https://github.com/RetailMeNotSandbox/dart/blob/master/src/python/dart/engine/emr/actions/terminate_datastore.py#L15

This is bad because it will cause scheduled triggers to fail since Workflows can only kick off when cluster state is ACTIVE. @dannymcpherson Is there a particular reason why the emr state should not be set to ACTIVE after a workflow is done?

**Comment by dannymcpherson** [comment]
Once an EMR cluster is shutdown, you cannot get that specific instance back (unlike Redshift).  For the use case you are referring to with workflows, I believe all you need to do is use a [datastore template](https://github.com/RetailMeNotSandbox/dart/blob/master/src/python/dart/service/workflow.py#L250) to ensure a new one is instantiated each time.  Make sense?

**Comment by maybeiambatman** [comment]
@dannymcpherson Makes sense. Thanks for clearing this up Danny! Closing.
