### ISSUE TITLE
Implement api for metadata sniffer tool on Datasets

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#4]
Implement creation of datasets with a helper metadata sniffing tool. Hitting this api with the s3 path to a dataset returns it's best guess of metadata regarding the dataset. These are the mvp features of the sniffer tool:

- Supports delimited datasets in s3
- Supports compression types ascii text, gzip and bzip
- Implies data types of each column from first X lines
- Returns a dict as response

**Comment by maybeiambatman** [comment]
@dannymcpherson If you could review the initial commit that would be great!

**Comment by dannymcpherson** [comment]
@maybeiambatman - Sorry for the delays.  Comments added.

**Comment by dannymcpherson** [comment]
One thing I noticed with ```hunch.infer_data``` is that the return value does not match the structure of a ```dataset```.  It needs to if we are going to use it as a form model default on the front end.  Also, look through the [dataset model](https://github.com/RetailMeNotSandbox/dart/blob/master/src/python/dart/model/dataset.py#L44) and see if other fields can be guessed (e.g. location, compression, etc).

**Comment by maybeiambatman** [comment]
Alright. Going to return a ```dataset``` as the response object.

**Comment by maybeiambatman** [comment]
I have addressed all of the issues raised by y'all in the last two commits. Would love for @dannymcpherson @geota @jsteigs642 to have another look!

**Comment by geota** [comment]
@maybeiambatman I made a couple comments on the latest changes. Rest lgtm

**Comment by maybeiambatman** [comment]
Ok made the changes. Closing this issue.
