### ISSUE TITLE
s3_engine: Support data_check using the S3 Object's Last Modified Date

### ISSUE THREAD

**Issue by geota** [RetailMeNotSandbox/dart#5]
Currently we support S3 data checks using data substitution tokens into the S3 object key.

This only works if the dataset embeds that information into the the S3 object's key. A number of truncate-load all datasets do not follow this pattern. For these types of datasets, we need to support checking the s3 object's last modified date.

**Comment by dannymcpherson** [comment]
@geota - Would it be sufficient to check the last modified date of the first file listed under a dataset's s3 location?
