### ISSUE TITLE
Fix regex filter for emails in action creation

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#6]
The email regex filters raises exception when we try to create an action with '-' separated email. e.g. "example-email+env@company.com"

**Comment by dannymcpherson** [comment]
I think it is just a matter of adjusting [this](https://github.com/RetailMeNotSandbox/dart/blob/master/src/python/dart/schema/base.py#L46) line.

**Comment by maybeiambatman** [comment]
This is working as expected. The bug was reported because people were confused by the UI.

Users assumed that they needed to click the Add button to confirm the email they had entered. Whereas, simple clicking the add button creates a second email point that is essentially None. The refex filter fails to validate the None object.

Attached screenshot for clarity.
![screen shot 2016-05-17 at 4 39 11 pm](https://cloud.githubusercontent.com/assets/2461323/15340284/434bdd3c-1c4e-11e6-90d7-e3dd38883ea9.png)
