### ISSUE TITLE
Implement ui for metadata sniffer tool on Datasets

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#8]
This is the other half of work that needs to be done to expose #4 to the user interface.

**Comment by maybeiambatman** [comment]
@geota @dannymcpherson @jsteigs642 Implemented. I'm sure y'all will find ways to improve the code. Will love some review on this.

**Comment by dannymcpherson** [comment]
@maybeiambatman - It looks like you are going down the right path.  Two things:

1. Can you squash your commits and push to a separate branch?  That will make it easier to read
2. I recommend getting rid of the "hunch" name in favor of something like "dataset_guess".  Seeing "hunch" only makes sense if you have all the context, where as "dataset_guess" (or something similar) is easier to understand without having to trace through the code base.

What do you think?

**Comment by maybeiambatman** [comment]
@dannymcpherson 

1. I will rebase and squash the commits. Hopefully that is much better to understand.
2. I have been thinking about that too. I will refactor all the names and follow up with you.

**Comment by maybeiambatman** [comment]
@dannymcpherson Should be much easier to see the changes now :)

**Comment by dannymcpherson** [comment]
:shipit:

**Comment by maybeiambatman** [comment]
Merging and closing this issue! Thanks everyone for the help.
