### ISSUE TITLE
Enable emr_engine start_datastore action to set PYSPARK_PYTHON

### ISSUE THREAD

**Issue by zroadhouse-rmn** [RetailMeNotSandbox/dart#80]
As part of an EMR workflow, I'd like to be able to set PYSPARK_PYTHON to switch to a different python besides the default system python. This can be done using the "configurations" argument of "aws emr create-cluster". The details are described in this link:

https://aws.amazon.com/blogs/big-data/using-python-3-4-on-emr-spark-applications/

My requested implementation in dart would be to allow my to specify additional configuration blocks in my start_datastore action. These blocks would be merged into the default start_configs.json using "Classification" as the merge key.

**Comment by zroadhouse-rmn** [comment]
More documentation:

http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-configure-apps.html

**Comment by maybeiambatman** [comment]
@zroadhouse-rmn we can close this, correct?

**Comment by zroadhouse-rmn** [comment]
Yes - resolved by #81
